// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var CharacterRelationship = struct {
	ProjectID      field.Number[uint64]
	CharacterID    field.Number[uint64]
	RelationCharID field.Number[uint64]
	Description    field.String
}{
	ProjectID:      field.Number[uint64]{}.WithColumn("project_id"),
	CharacterID:    field.Number[uint64]{}.WithColumn("character_id"),
	RelationCharID: field.Number[uint64]{}.WithColumn("relation_char_id"),
	Description:    field.String{}.WithColumn("description"),
}
