// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var Character = struct {
	ProjectID       field.Number[uint64]
	Name            field.String
	RoleType        field.String
	Avatar          field.String
	PopularityScore field.Number[int]
	ImportanceScore field.Number[int]
	ActivityScore   field.Number[int]
	Personality     field.String
	Motivation      field.String
	Goal            field.String
	Conflict        field.String
	Epiphany        field.String
	DetailedBio     field.String
	Notes           field.String
}{
	ProjectID:       field.Number[uint64]{}.WithColumn("project_id"),
	Name:            field.String{}.WithColumn("name"),
	RoleType:        field.String{}.WithColumn("role_type"),
	Avatar:          field.String{}.WithColumn("avatar"),
	PopularityScore: field.Number[int]{}.WithColumn("popularity_score"),
	ImportanceScore: field.Number[int]{}.WithColumn("importance_score"),
	ActivityScore:   field.Number[int]{}.WithColumn("activity_score"),
	Personality:     field.String{}.WithColumn("personality"),
	Motivation:      field.String{}.WithColumn("motivation"),
	Goal:            field.String{}.WithColumn("goal"),
	Conflict:        field.String{}.WithColumn("conflict"),
	Epiphany:        field.String{}.WithColumn("epiphany"),
	DetailedBio:     field.String{}.WithColumn("detailed_bio"),
	Notes:           field.String{}.WithColumn("notes"),
}
