// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var CharacterTrait = struct {
	ProjectID    field.Number[uint64]
	Name         field.String
	Description  field.String
	MinValue     field.Number[float64]
	MaxValue     field.Number[float64]
	DefaultValue field.Number[float64]
}{
	ProjectID:    field.Number[uint64]{}.WithColumn("project_id"),
	Name:         field.String{}.WithColumn("name"),
	Description:  field.String{}.WithColumn("description"),
	MinValue:     field.Number[float64]{}.WithColumn("min_value"),
	MaxValue:     field.Number[float64]{}.WithColumn("max_value"),
	DefaultValue: field.Number[float64]{}.WithColumn("default_value"),
}
