// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var BaseModel = struct {
	ID        field.Number[uint64]
	CreatedAt field.Number[int64]
	UpdatedAt field.Number[int64]
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	CreatedAt: field.Number[int64]{}.WithColumn("created_at"),
	UpdatedAt: field.Number[int64]{}.WithColumn("updated_at"),
}

var BaseDeleteModel = struct {
	ID        field.Number[uint64]
	CreatedAt field.Number[int64]
	UpdatedAt field.Number[int64]
	DeletedAt field.Field[gorm.DeletedAt]
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	CreatedAt: field.Number[int64]{}.WithColumn("created_at"),
	UpdatedAt: field.Number[int64]{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
