// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var Item = struct {
	ProjectID   field.Number[uint64]
	Name        field.String
	Type        field.String
	SubType     field.String
	Rarity      field.Number[int]
	Description field.String
	OwnerType   field.String
	OwnerID     field.Number[uint64]
	Appearance  field.String
	IconURL     field.String
	Notes       field.String
}{
	ProjectID:   field.Number[uint64]{}.WithColumn("project_id"),
	Name:        field.String{}.WithColumn("name"),
	Type:        field.String{}.WithColumn("type"),
	SubType:     field.String{}.WithColumn("sub_type"),
	Rarity:      field.Number[int]{}.WithColumn("rarity"),
	Description: field.String{}.WithColumn("description"),
	OwnerType:   field.String{}.WithColumn("owner_type"),
	OwnerID:     field.Number[uint64]{}.WithColumn("owner_id"),
	Appearance:  field.String{}.WithColumn("appearance"),
	IconURL:     field.String{}.WithColumn("icon_url"),
	Notes:       field.String{}.WithColumn("notes"),
}
