// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var ItemHistory = struct {
	ProjectID     field.Number[uint64]
	ItemID        field.Number[uint64]
	StoryEventID  field.Number[uint64]
	Action        field.String
	FromOwnerType field.String
	FromOwnerID   field.Number[uint64]
	ToOwnerType   field.String
	ToOwnerID     field.Number[uint64]
	Quantity      field.Number[int]
	Note          field.String
}{
	ProjectID:     field.Number[uint64]{}.WithColumn("project_id"),
	ItemID:        field.Number[uint64]{}.WithColumn("item_id"),
	StoryEventID:  field.Number[uint64]{}.WithColumn("story_event_id"),
	Action:        field.String{}.WithColumn("action"),
	FromOwnerType: field.String{}.WithColumn("from_owner_type"),
	FromOwnerID:   field.Number[uint64]{}.WithColumn("from_owner_id"),
	ToOwnerType:   field.String{}.WithColumn("to_owner_type"),
	ToOwnerID:     field.Number[uint64]{}.WithColumn("to_owner_id"),
	Quantity:      field.Number[int]{}.WithColumn("quantity"),
	Note:          field.String{}.WithColumn("note"),
}
