// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var ItemState = struct {
	ProjectID    field.Number[uint64]
	ItemID       field.Number[uint64]
	StoryEventID field.Number[uint64]
	TraitID      field.Number[uint64]
	TraitValue   field.Number[float64]
	Note         field.String
}{
	ProjectID:    field.Number[uint64]{}.WithColumn("project_id"),
	ItemID:       field.Number[uint64]{}.WithColumn("item_id"),
	StoryEventID: field.Number[uint64]{}.WithColumn("story_event_id"),
	TraitID:      field.Number[uint64]{}.WithColumn("trait_id"),
	TraitValue:   field.Number[float64]{}.WithColumn("trait_value"),
	Note:         field.String{}.WithColumn("note"),
}
