// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var Location = struct {
	ProjectID   field.Number[uint64]
	Name        field.String
	Type        field.String
	SubType     field.String
	Description field.String
	ParentID    field.Number[uint64]
	Path        field.String
	X           field.Number[float64]
	Y           field.Number[float64]
	Z           field.Number[float64]
	Appearance  field.String
	IconURL     field.String
	Notes       field.String
}{
	ProjectID:   field.Number[uint64]{}.WithColumn("project_id"),
	Name:        field.String{}.WithColumn("name"),
	Type:        field.String{}.WithColumn("type"),
	SubType:     field.String{}.WithColumn("sub_type"),
	Description: field.String{}.WithColumn("description"),
	ParentID:    field.Number[uint64]{}.WithColumn("parent_id"),
	Path:        field.String{}.WithColumn("path"),
	X:           field.Number[float64]{}.WithColumn("x"),
	Y:           field.Number[float64]{}.WithColumn("y"),
	Z:           field.Number[float64]{}.WithColumn("z"),
	Appearance:  field.String{}.WithColumn("appearance"),
	IconURL:     field.String{}.WithColumn("icon_url"),
	Notes:       field.String{}.WithColumn("notes"),
}
