// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var Project = struct {
	UserID               field.Number[uint64]
	Title                field.String
	Description          field.String
	Genre                field.String
	WorldTimePeriod      field.String
	WorldLocation        field.String
	WorldAtmosphere      field.String
	WorldRules           field.String
	TargetWords          field.Number[int]
	CurrentWords         field.Number[int]
	Status               field.String
	NarrativePerspective field.String
	WritingStyleID       field.Number[uint64]
}{
	UserID:               field.Number[uint64]{}.WithColumn("user_id"),
	Title:                field.String{}.WithColumn("title"),
	Description:          field.String{}.WithColumn("description"),
	Genre:                field.String{}.WithColumn("genre"),
	WorldTimePeriod:      field.String{}.WithColumn("world_time_period"),
	WorldLocation:        field.String{}.WithColumn("world_location"),
	WorldAtmosphere:      field.String{}.WithColumn("world_atmosphere"),
	WorldRules:           field.String{}.WithColumn("world_rules"),
	TargetWords:          field.Number[int]{}.WithColumn("target_words"),
	CurrentWords:         field.Number[int]{}.WithColumn("current_words"),
	Status:               field.String{}.WithColumn("status"),
	NarrativePerspective: field.String{}.WithColumn("narrative_perspective"),
	WritingStyleID:       field.Number[uint64]{}.WithColumn("writing_style_id"),
}
