// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/datatypes"
)

var StoryEvent = struct {
	ProjectID               field.Number[uint64]
	Seq                     field.Number[int]
	Title                   field.String
	Summary                 field.String
	PovCharacterID          field.Number[uint64]
	Goal                    field.String
	Conflict                field.String
	Outcome                 field.String
	IsUsed                  field.Bool
	ChapterID               field.Number[uint64]
	SceneType               field.String
	Location                field.String
	TimeSetting             field.String
	EmotionalTone           field.String
	ParticipatingCharacters field.Field[datatypes.JSON]
}{
	ProjectID:               field.Number[uint64]{}.WithColumn("project_id"),
	Seq:                     field.Number[int]{}.WithColumn("seq"),
	Title:                   field.String{}.WithColumn("title"),
	Summary:                 field.String{}.WithColumn("summary"),
	PovCharacterID:          field.Number[uint64]{}.WithColumn("pov_character_id"),
	Goal:                    field.String{}.WithColumn("goal"),
	Conflict:                field.String{}.WithColumn("conflict"),
	Outcome:                 field.String{}.WithColumn("outcome"),
	IsUsed:                  field.Bool{}.WithColumn("is_used"),
	ChapterID:               field.Number[uint64]{}.WithColumn("chapter_id"),
	SceneType:               field.String{}.WithColumn("scene_type"),
	Location:                field.String{}.WithColumn("location"),
	TimeSetting:             field.String{}.WithColumn("time_setting"),
	EmotionalTone:           field.String{}.WithColumn("emotional_tone"),
	ParticipatingCharacters: field.Field[datatypes.JSON]{}.WithColumn("participating_characters"),
}
