// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var User = struct {
	Username      field.String
	Email         field.String
	Password      field.String
	OAuthProvider field.String
	OAuthID       field.String
	DisplayName   field.String
	AvatarURL     field.String
	Status        field.String
}{
	Username:      field.String{}.WithColumn("username"),
	Email:         field.String{}.WithColumn("email"),
	Password:      field.String{}.WithColumn("password"),
	OAuthProvider: field.String{}.WithColumn("o_auth_provider"),
	OAuthID:       field.String{}.WithColumn("o_auth_id"),
	DisplayName:   field.String{}.WithColumn("display_name"),
	AvatarURL:     field.String{}.WithColumn("avatar_url"),
	Status:        field.String{}.WithColumn("status"),
}
